### PR TITLE
feat: prompt select account

### PR DESCRIPTION
**Pull request by pr-Mais**
Fixes an issue on Windows where the user can't select account if signed in with multiple accounts on Chrome.
See https://github.com/invertase/flutterfire_desktop/issues/46

### CODE REVIEW

**Comment by long1eu** [comment]
Looks good, but maybe we should allow the developer access to this variable so he could change it.

**Comment by pr-Mais** [comment]
Would make sense to allow passing a Map of additional parameters or just `prompt`?

**Comment by long1eu** [comment]
Thank you for your help. 🤗

**Comment by pr-Mais** [comment]
Thank you too!

**Comment by pr-Mais** [comment]
Can we release this update to close the issue on FlutterFire

**Comment by long1eu** [comment]
https://pub.dev/packages/google_sign_in_dartio done

**Pull request merged**
